In [2]:
from gensim.models import Word2Vec, KeyedVectors
pathToGoogleNews300 = '..//fromBlogOfShaneLynnWordEmbeddingsWithSpacyAndGensim_GoogleNews300//data//GoogleNews-vectors-negative300.bin'
#pathToGoogleNews300 = 'data\GoogleNews-vectors-negative300.bin'
model = KeyedVectors.load_word2vec_format(pathToGoogleNews300, binary=True)

In [29]:
model.most_similar(positive=['Oscar_Wilde', 'woman'], negative=['man'])

[('Jane_Austen', 0.6260595321655273),
 ('Noël_Coward', 0.600019097328186),
 ('Madame_Bovary', 0.5772191286087036),
 ('Charlotte_Bronte', 0.5637412667274475),
 ('Somerset_Maugham', 0.5583583116531372),
 ('Noel_Coward', 0.5572813749313354),
 ('Bernard_Shaw', 0.5557636022567749),
 ('DH_Lawrence', 0.5536727905273438),
 ('Antonia_Fraser', 0.5471805334091187),
 ('An_Ideal_Husband', 0.541670024394989)]

In [2]:
model.wv.syn0.shape

<ipython-input-2-b77a3a51ff8b>:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  model.wv.syn0.shape
<ipython-input-2-b77a3a51ff8b>:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.vectors instead).
  model.wv.syn0.shape


(3000000, 300)

In [3]:
type(model.wv.syn0)

<ipython-input-3-d6842a29120c>:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  type(model.wv.syn0)
<ipython-input-3-d6842a29120c>:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.vectors instead).
  type(model.wv.syn0)


numpy.ndarray

In [4]:
model.doesnt_match("man woman child kitchen".split())

C:\Users\Eric\anaconda3\lib\site-packages\gensim\models\keyedvectors.py:877: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  vectors = vstack(self.word_vec(word, use_norm=True) for word in used_words).astype(REAL)


'kitchen'

In [5]:
model.most_similar(positive=['king', 'woman'], negative=['man'])

[('queen', 0.7118192911148071),
 ('monarch', 0.6189674139022827),
 ('princess', 0.5902431607246399),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377321243286133),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.5181134343147278),
 ('sultan', 0.5098593235015869),
 ('monarchy', 0.5087411999702454)]

In [6]:
model.most_similar("man")

[('woman', 0.7664012312889099),
 ('boy', 0.6824870109558105),
 ('teenager', 0.6586930751800537),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409236907959),
 ('teen_ager', 0.5549196004867554),
 ('men', 0.5489763021469116)]

In [7]:
import pandas as pd

pathToGungorVict = '..//..//DS7004//u1720146_DS7004_courseworkCodeAndData//preparationWorks//fromDS7003_Gungor2018VictorianAuthorAttribution_NGram//Gungor_2018_VictorianAuthorAttribution_data-train.csv'
gungorVictRow = pd.read_csv(pathToGungorVict, encoding = 'ISO-8859-1')
#13 is Frances Hodgson Burnett and 22 is Jacob Abbott

In [8]:
burnett13 = gungorVictRow.loc[gungorVictRow['author'] == 13]

abbott22 = gungorVictRow.loc[gungorVictRow['author'] == 22]

b13a22 = burnett13.append(abbott22, ignore_index=True)

test = b13a22.sample(frac=0.3, random_state=42)
test = test.reset_index()

train = b13a22.drop(test.index)
train = train.sample(frac=1, random_state=42).reset_index()

In [42]:
test.shape

(294, 3)

In [9]:
print(test.index)

RangeIndex(start=0, stop=294, step=1)


In [10]:
print(train.index)

RangeIndex(start=0, stop=686, step=1)


In [11]:
test

index                                               text  author
0      788  turned round and seemed to be going along in a...      22
1      440  put into her first breadth ax anyway each memb...      13
2      139  speech before the night was ended and he endea...      13
3      695  do they all begin to shine together which do w...      22
4       66  under their charge applied their and when they...      13
..     ...                                                ...     ...
289    784  ushered as they walked from the station into t...      22
290    757  little bat he rubbed them and they soon became...      22
291    930  left the dam however they put the three in aga...      22
292    915  hers have in some cases done the author the ho...      22
293    394  room his hair was in high disorder and his cou...      13

[294 rows x 3 columns]

In [12]:
train

index                                               text  author
0      580  grateful feeling toward the yes sir and someti...      22
1      946  en and contrive to block it up level john s wo...      22
2      551  were crouched in a corner of their cage where ...      22
3      630  stopped to wrap herself in her cloak and then ...      22
4      612  for this world you had better be off m said no...      22
..     ...                                                ...     ...
681    365  i wouldn t do my best by â an i ain t but a fa...      13
682    400  be built if justice were done to them was nour...      13
683    564  a few times into the green log he gave these b...      22
684    729  or other that he gave it up to you for instanc...      22
685    396  result of the policy of a government which had...      13

[686 rows x 3 columns]

In [13]:
import gensim
all_stopwords = set(gensim.parsing.preprocessing.STOPWORDS)
all_stopwords

{'a',
 'about',
 'above',
 'across',
 'after',
 'afterwards',
 'again',
 'against',
 'all',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'amoungst',
 'amount',
 'an',
 'and',
 'another',
 'any',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anywhere',
 'are',
 'around',
 'as',
 'at',
 'back',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'behind',
 'being',
 'below',
 'beside',
 'besides',
 'between',
 'beyond',
 'bill',
 'both',
 'bottom',
 'but',
 'by',
 'call',
 'can',
 'cannot',
 'cant',
 'co',
 'computer',
 'con',
 'could',
 'couldnt',
 'cry',
 'de',
 'describe',
 'detail',
 'did',
 'didn',
 'do',
 'does',
 'doesn',
 'doing',
 'don',
 'done',
 'down',
 'due',
 'during',
 'each',
 'eg',
 'eight',
 'either',
 'eleven',
 'else',
 'elsewhere',
 'empty',
 'enough',
 'etc',
 'even',
 'ever',
 'every',
 'everyone',
 'everything',
 'everywhere',
 'except',
 'few',
 'fifte

In [14]:
#be careful: nword and counter must be integers --Chiu
import numpy as np  # Make sure that numpy is imported

def makeFeatureVec(words, model, num_features):
    # Function to average all of the word vectors in a given
    # paragraph
    #
    # Pre-initialize an empty numpy array (for speed)
    featureVec = np.zeros((num_features,),dtype="float32")
    #
    nwords = 0
    # 
    # Index2word is a list that contains the names of the words in 
    # the model's vocabulary. Convert it to a set, for speed 
    index2word_set = set(model.wv.index2word)
    index2word_set2 = all_stopwords
    #
    # Loop over each word in the review and, if it is in the model's
    # vocaublary, add its feature vector to the total
    for word in words:
        if word in index2word_set and word in index2word_set2: 
            nwords = nwords + 1
            featureVec = np.add(featureVec,model[word])
    # 
    # Divide the result by the number of words to get the average
    if nwords == 0:
        nwords = 1
    featureVec = np.divide(featureVec,nwords)
    return featureVec


def getAvgFeatureVecs(reviews, model, num_features):
    # Given a set of reviews (each one a list of words), calculate 
    # the average feature vector for each one and return a 2D numpy array 
    # 
    # Initialize a counter
    counter = 0
    # 
    # Preallocate a 2D numpy array, for speed
    reviewFeatureVecs = np.zeros((len(reviews),num_features),dtype="float32")
    # 
    # Loop through the reviews
    for review in reviews:
       #
       # Print a status message every 1000th review
        if counter%50 == 0:
            haha = counter; hihi = len(reviews)
            print(f"Review {haha} of {hihi}") #% (counter, len(reviews))
       # 
       # Call the function (defined above) that makes average feature vectors
        #reviewFeatureVecs[counter] = makeFeatureVec(review, model, num_features)
        reviewFeatureVecs[counter] = makeFeatureVec(review, model, num_features)
       #
       # Increment the counter
        counter = counter + 1
    return reviewFeatureVecs

In [15]:
# Import various modules for string cleaning
from bs4 import BeautifulSoup
import re
from nltk.corpus import stopwords

def review_to_wordlist( review, remove_stopwords=False ):
    # Function to convert a document to a sequence of words,
    # optionally removing stop words.  Returns a list of words.
    #
    # 1. Remove HTML
    review_text = BeautifulSoup(review).get_text()
    #  
    # 2. Remove non-letters
    review_text = re.sub("[^a-zA-Z]"," ", review_text)
    #
    # 3. Convert words to lower case and split them
    words = review_text.lower().split()
    #
    # 4. Optionally remove stop words (false by default)
    if remove_stopwords:
        stops = set(stopwords.words("english"))
        words = [w for w in words if not w in stops]
    #
    # 5. Return a list of words
    return(words)

In [16]:
# ****************************************************************
# Calculate average feature vectors for training and testing sets,
# using the functions we defined above. Notice that we now use stop word
# removal.
num_features = 300
clean_train_reviews = []
for review in train["text"]:
    #clean_train_reviews.append( review_to_wordlist( review, \
        #remove_stopwords=True ))
    clean_train_reviews.append( review_to_wordlist( review ))

trainDataVecs = getAvgFeatureVecs( clean_train_reviews, model, num_features )

print("Creating average feature vecs for test reviews")
clean_test_reviews = []
for review in test["text"]:
    #clean_test_reviews.append( review_to_wordlist( review, remove_stopwords=True ))
    clean_test_reviews.append( review_to_wordlist( review ))

testDataVecs = getAvgFeatureVecs( clean_test_reviews, model, num_features )

Review 0 of 686


<ipython-input-14-8856e0a8f420>:15: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  index2word_set = set(model.wv.index2word)


Review 50 of 686
Review 100 of 686
Review 150 of 686
Review 200 of 686
Review 250 of 686
Review 300 of 686
Review 350 of 686
Review 400 of 686
Review 450 of 686
Review 500 of 686
Review 550 of 686
Review 600 of 686
Review 650 of 686
Creating average feature vecs for test reviews
Review 0 of 294
Review 50 of 294
Review 100 of 294
Review 150 of 294
Review 200 of 294
Review 250 of 294


In [17]:
# Fit a random forest to the training data, using 100 trees
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier( n_estimators = 100 )

print("Fitting a random forest to labeled training data...")
forest = forest.fit( trainDataVecs, train["author"] )

# Test & extract results 
result = forest.predict( testDataVecs )

# Write the test results 
output = pd.DataFrame( data={"true_author":test["author"], "pred_author":result} )
output.to_csv( "Word2Vec_AverageVectors.csv", index=False, quoting=3 )

Fitting a random forest to labeled training data...


In [18]:
print(output)

     true_author  pred_author
0             22           22
1             13           13
2             13           13
3             22           22
4             13           13
..           ...          ...
289           22           22
290           22           22
291           22           22
292           22           22
293           13           13

[294 rows x 2 columns]


In [19]:
confusion_matrix = pd.crosstab(output['true_author'], output['pred_author'], rownames=['Actural'], colnames=['Predicted'])
print(confusion_matrix)

Predicted   13   22
Actural            
13         141    6
22           0  147


In [22]:
import sklearn
sklearn.metrics.confusion_matrix(output['true_author'], output['pred_author'])

array([[141,   6],
       [  0, 147]], dtype=int64)

In [23]:
sklearn.metrics.precision_recall_fscore_support(output['true_author'], output['pred_author'], average=None)

(array([1.        , 0.96078431]),
 array([0.95918367, 1.        ]),
 array([0.97916667, 0.98      ]),
 array([147, 147], dtype=int64))

In [29]:
import numpy as np
from sklearn.metrics import precision_recall_fscore_support
y_true = np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])
y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])
precision_recall_fscore_support(y_true, y_pred, average='macro')

(0.2222222222222222, 0.3333333333333333, 0.26666666666666666, None)

In [30]:
precision_recall_fscore_support(y_true, y_pred, average='micro')

(0.3333333333333333, 0.3333333333333333, 0.3333333333333333, None)

In [31]:
precision_recall_fscore_support(y_true, y_pred, average='weighted')

(0.2222222222222222, 0.3333333333333333, 0.26666666666666666, None)

In [36]:
precision_recall_fscore_support(y_true, y_pred, average=None)

(array([0.66666667, 0.        , 0.        ]),
 array([1., 0., 0.]),
 array([0.8, 0. , 0. ]),
 array([2, 2, 2], dtype=int64))

In [35]:
precision_recall_fscore_support(y_true, y_pred, labels=['cat'])

(array([0.66666667]), array([1.]), array([0.8]), array([2], dtype=int64))

In [33]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_true, y_pred)

array([[2, 0, 0],
       [1, 0, 1],
       [0, 2, 0]], dtype=int64)

In [38]:
pd.DataFrame(output.pred_author.value_counts()) #equivalent to table of R

pred_author
22          153
13          141