In [8]:
from gensim.models import KeyedVectors

In [10]:
# Load vectors directly from the file
model = KeyedVectors.load_word2vec_format('data//GoogleNews-vectors-negative300.bin', binary=True)

In [16]:
# Access vectors for specific words with a keyed lookup:
vector = model['easy']
vector

array([ 3.06640625e-01,  6.83593750e-02, -1.60156250e-01,  1.19628906e-01,
       -6.56127930e-03,  4.39453125e-03,  1.44531250e-01,  6.20117188e-02,
        7.17773438e-02,  2.67333984e-02,  9.91210938e-02, -2.30712891e-02,
        5.66406250e-02, -1.74804688e-01, -5.32226562e-02,  8.98437500e-02,
        2.94921875e-01, -6.59179688e-02,  1.35742188e-01, -1.73828125e-01,
        7.32421875e-02,  2.08007812e-01,  7.27539062e-02,  2.19726562e-01,
       -5.02929688e-02, -1.15234375e-01, -1.80664062e-01, -4.29153442e-06,
       -1.69921875e-01, -7.61718750e-02, -4.30297852e-03,  1.71875000e-01,
        2.57812500e-01, -1.33789062e-01,  3.95507812e-02,  4.24194336e-03,
       -2.80761719e-02, -1.54296875e-01,  1.76757812e-01,  6.68945312e-02,
        2.71484375e-01, -1.43554688e-01,  4.02343750e-01, -1.19140625e-01,
       -2.58789062e-02, -5.63964844e-02,  3.78417969e-02,  4.29687500e-02,
        2.92968750e-02, -2.11181641e-02, -4.15039062e-02,  6.29882812e-02,
       -1.90429688e-02, -

In [15]:
# see the shape of the vector (300,)
vector.shape

(300,)

In [17]:
type(vector)

numpy.ndarray

In [22]:
vector1 = model['hello']
vector1

array([-0.05419922,  0.01708984, -0.00527954,  0.33203125, -0.25      ,
       -0.01397705, -0.15039062, -0.265625  ,  0.01647949,  0.3828125 ,
       -0.03295898, -0.09716797, -0.16308594, -0.04443359,  0.00946045,
        0.18457031,  0.03637695,  0.16601562,  0.36328125, -0.25585938,
        0.375     ,  0.171875  ,  0.21386719, -0.19921875,  0.13085938,
       -0.07275391, -0.02819824,  0.11621094,  0.15332031,  0.09082031,
        0.06787109, -0.0300293 , -0.16894531, -0.20800781, -0.03710938,
       -0.22753906,  0.26367188,  0.012146  ,  0.18359375,  0.31054688,
       -0.10791016, -0.19140625,  0.21582031,  0.13183594, -0.03515625,
        0.18554688, -0.30859375,  0.04785156, -0.10986328,  0.14355469,
       -0.43554688, -0.0378418 ,  0.10839844,  0.140625  , -0.10595703,
        0.26171875, -0.17089844,  0.39453125,  0.12597656, -0.27734375,
       -0.28125   ,  0.14746094, -0.20996094,  0.02355957,  0.18457031,
        0.00445557, -0.27929688, -0.03637695, -0.29296875,  0.19

In [25]:
vector2 = model['world']
vector2

array([-6.39648438e-02,  6.83593750e-02,  2.24609375e-01,  1.31835938e-01,
       -5.95703125e-02,  3.88183594e-02,  7.56835938e-02, -1.41601562e-01,
        7.08007812e-02,  1.51367188e-01, -8.83789062e-02, -6.88476562e-02,
        2.05078125e-01, -2.11914062e-01, -1.10351562e-01,  9.57031250e-02,
       -8.15429688e-02,  2.13867188e-01,  1.62109375e-01,  3.93066406e-02,
       -7.81250000e-02,  7.66601562e-02,  9.08203125e-02, -8.98437500e-02,
        9.13085938e-02,  2.14843750e-02, -2.61718750e-01,  6.05468750e-02,
       -5.59082031e-02, -1.35742188e-01, -1.33666992e-02, -5.24902344e-02,
       -1.85546875e-01,  7.61718750e-02,  1.03027344e-01, -3.05175781e-02,
       -1.60156250e-01, -8.10546875e-02,  1.36718750e-01,  1.43554688e-01,
       -2.57568359e-02,  1.64062500e-01, -4.51660156e-02,  2.89062500e-01,
        2.13867188e-01,  3.30078125e-01, -5.43212891e-03, -1.20544434e-03,
       -8.49609375e-02,  1.86523438e-01, -1.74804688e-01,  7.71484375e-02,
        9.64355469e-03, -

In [26]:
# Processing sentences is not as simple as with Spacy:
vectors = [model[x] for x in "This is some text I am processing with Spacy".split(' ')]
vectors

[array([-0.2890625 ,  0.19921875,  0.16015625,  0.02526855, -0.23632812,
         0.10205078,  0.06640625, -0.16503906,  0.12597656,  0.22070312,
         0.05517578, -0.28710938, -0.02148438,  0.05541992,  0.01574707,
         0.29296875,  0.19433594, -0.01531982,  0.03955078, -0.21484375,
         0.00994873,  0.16015625,  0.07958984, -0.05932617,  0.12353516,
        -0.27148438, -0.10205078,  0.078125  , -0.07519531,  0.22363281,
         0.16210938, -0.04614258,  0.12304688,  0.07275391,  0.25      ,
         0.0072937 , -0.38867188,  0.10644531,  0.20996094,  0.06103516,
         0.10107422,  0.16894531, -0.15429688, -0.08251953,  0.06542969,
        -0.12255859, -0.11621094,  0.04248047,  0.08251953,  0.09716797,
        -0.05371094,  0.125     ,  0.15039062, -0.09228516,  0.23925781,
         0.15234375,  0.1796875 , -0.26171875,  0.15429688,  0.09619141,
        -0.30859375, -0.05224609, -0.18652344, -0.24414062, -0.0612793 ,
        -0.12695312,  0.14160156, -0.03295898,  0.0

In [27]:
type(vectors)

list

In [29]:
vector.shape

(300,)

In [30]:
shape(vectors)

NameError: name 'shape' is not defined

In [31]:
len(vectors)

9